FROM ghcr.io/labrats-work/ops-images/python:latest

COPY ./src/pyfi_core/ ./pyfi_core
RUN pip3 install ./pyfi_core

COPY ./src/pyfi_server/ ./pyfi_server
RUN pip3 install ./pyfi_server

CMD ["python", "-u", "-m" , "pyfi_server"]